import jsPDF from "jspdf";
import QRCode from "qrcode";
import { money, shortDate } from "./format";

export type LandlordPaymentReportItem = {
  id?: string;
  amount: number | string;
  paid_at: string;
  method?: string | null;
  reference?: string | null;
  period_label?: string | null;
  status?: string | null;
  notes?: string | null;
  tenant_name?: string | null;
  tenant_phone?: string | null;
  property_name?: string | null;
  unit_name?: string | null;
  tenants?: {
    full_name?: string | null;
    phone?: string | null;
  } | null;
  properties?: {
    name?: string | null;
  } | null;
  units?: {
    unit_number?: string | null;
    room_number?: string | null;
  } | null;
};

export type LandlordReportMeta = {
  company_name?: string | null;
  full_name?: string | null;
  email?: string | null;
  phone?: string | null;
  currency?: string | null;
  periodFilter?: string | null;
  methodFilter?: string | null;
};

export async function buildLandlordPaymentsPdf(
  payments: LandlordPaymentReportItem[],
  meta?: LandlordReportMeta,
) {
  const doc = new jsPDF({ unit: "pt", format: "a4" });
  const w = doc.internal.pageSize.getWidth();
  const h = doc.internal.pageSize.getHeight();
  const margin = 36;
  const contentWidth = w - margin * 2;

  const company = meta?.company_name || meta?.full_name || "RentReceipt Pro Landlord";
  const currency = meta?.currency || "KSh";
  const reportDate = new Date().toLocaleDateString("en-GB", {
    day: "numeric",
    month: "short",
    year: "numeric",
  });

  // Calculate totals
  const totalAmount = payments.reduce((sum, p) => sum + Number(p.amount || 0), 0);
  const mpesaTotal = payments
    .filter((p) => p.method === "mpesa")
    .reduce((sum, p) => sum + Number(p.amount || 0), 0);
  const kcbTotal = payments
    .filter((p) => p.method === "kcb" || p.method === "kcb_buni")
    .reduce((sum, p) => sum + Number(p.amount || 0), 0);
  const otherTotal = totalAmount - mpesaTotal - kcbTotal;

  // Generate verification QR code
  const origin = typeof window !== "undefined" ? window.location.origin : "https://www.rentreceipt.co.ke";
  const qrData = `${origin}/payments?verified=${Date.now()}&total=${totalAmount}`;
  let qrDataUrl = "";
  try {
    qrDataUrl = await QRCode.toDataURL(qrData, { margin: 1, width: 90 });
  } catch {}

  const drawHeader = (pageNumber: number, totalPagesPlaceholder = true) => {
    // Top Bar - Midnight Navy
    doc.setFillColor(11, 18, 32);
    doc.rect(0, 0, w, 85, "F");

    // Emerald Green Accent Line
    doc.setFillColor(16, 185, 129);
    doc.rect(0, 85, w, 3.5, "F");

    // Company / Landlord Info
    doc.setTextColor(255, 255, 255);
    doc.setFont("helvetica", "bold");
    doc.setFontSize(16);
    doc.text(company, margin, 36);

    doc.setFont("helvetica", "normal");
    doc.setFontSize(9);
    doc.setTextColor(203, 213, 225);
    doc.text("Official Landlord Rent Collections & Payments Statement", margin, 52);
    if (meta?.phone || meta?.email) {
      doc.text(`Contact: ${meta.phone || meta.email}`, margin, 66);
    }

    // Statement Header Details (Right aligned)
    doc.setFont("helvetica", "bold");
    doc.setFontSize(11);
    doc.setTextColor(52, 211, 153);
    doc.text("PAYMENTS STATEMENT", w - margin, 34, { align: "right" });

    doc.setFont("helvetica", "normal");
    doc.setFontSize(8.5);
    doc.setTextColor(203, 213, 225);
    doc.text(`Generated: ${reportDate}`, w - margin, 50, { align: "right" });
    doc.text(`Total Records: ${payments.length} Payments`, w - margin, 64, { align: "right" });
    doc.text("Status: VERIFIED AUDIT REPORT", w - margin, 77, { align: "right" });
  };

  const drawFooter = (pageNum: number, totalPages: number) => {
    doc.setFillColor(248, 250, 252);
    doc.rect(0, h - 35, w, 35, "F");

    doc.setDrawColor(226, 232, 240);
    doc.line(margin, h - 35, w - margin, h - 35);

    doc.setFont("helvetica", "normal");
    doc.setFontSize(8);
    doc.setTextColor(148, 163, 184);
    doc.text("Generated by RentReceiptPro · Secure Property & Rent Intelligence", margin, h - 16);
    doc.text(`Page ${pageNum} of ${totalPages}`, w - margin, h - 16, { align: "right" });
  };

  // Draw Page 1 Header
  drawHeader(1);

  // Summary Metrics Banner (Page 1 only)
  let y = 105;

  // Background Box for Metrics
  doc.setFillColor(241, 245, 249);
  doc.roundedRect(margin, y, contentWidth, 54, 8, 8, "F");
  doc.setDrawColor(203, 213, 225);
  doc.roundedRect(margin, y, contentWidth, 54, 8, 8, "S");

  // Metrics Columns
  const cardW = contentWidth / 4;

  // Card 1: Total Revenue
  doc.setFont("helvetica", "bold");
  doc.setFontSize(7.5);
  doc.setTextColor(100, 116, 139);
  doc.text("TOTAL COLLECTED", margin + 12, y + 18);
  doc.setFontSize(13);
  doc.setTextColor(5, 150, 105);
  doc.text(`${currency} ${totalAmount.toLocaleString("en-KE")}`, margin + 12, y + 38);

  // Card 2: M-Pesa STK Collections
  doc.setFontSize(7.5);
  doc.setTextColor(100, 116, 139);
  doc.text("M-PESA DARAJA", margin + cardW + 8, y + 18);
  doc.setFontSize(11);
  doc.setTextColor(15, 23, 42);
  doc.text(`${currency} ${mpesaTotal.toLocaleString("en-KE")}`, margin + cardW + 8, y + 38);

  // Card 3: KCB BUNI Collections
  doc.setFontSize(7.5);
  doc.setTextColor(100, 116, 139);
  doc.text("KCB BUNI PAYBILL", margin + cardW * 2 + 8, y + 18);
  doc.setFontSize(11);
  doc.setTextColor(37, 99, 235);
  doc.text(`${currency} ${kcbTotal.toLocaleString("en-KE")}`, margin + cardW * 2 + 8, y + 38);

  // Card 4: Other / Bank / Cash
  doc.setFontSize(7.5);
  doc.setTextColor(100, 116, 139);
  doc.text("BANK / CASH / OTHER", margin + cardW * 3 + 8, y + 18);
  doc.setFontSize(11);
  doc.setTextColor(15, 23, 42);
  doc.text(`${currency} ${otherTotal.toLocaleString("en-KE")}`, margin + cardW * 3 + 8, y + 38);

  y += 72;

  // Table Column Definitions
  const colX = {
    num: margin + 6,
    date: margin + 28,
    tenant: margin + 95,
    unit: margin + 215,
    method: margin + 300,
    ref: margin + 365,
    period: margin + 440,
    amount: w - margin - 8,
  };

  const drawTableHeader = (yPos: number) => {
    doc.setFillColor(15, 23, 42);
    doc.roundedRect(margin, yPos, contentWidth, 22, 4, 4, "F");

    doc.setFont("helvetica", "bold");
    doc.setFontSize(8);
    doc.setTextColor(255, 255, 255);

    doc.text("#", colX.num, yPos + 14);
    doc.text("DATE", colX.date, yPos + 14);
    doc.text("TENANT NAME", colX.tenant, yPos + 14);
    doc.text("PROPERTY / UNIT", colX.unit, yPos + 14);
    doc.text("METHOD", colX.method, yPos + 14);
    doc.text("REFERENCE", colX.ref, yPos + 14);
    doc.text("PERIOD", colX.period, yPos + 14);
    doc.text("AMOUNT (KSH)", colX.amount, yPos + 14, { align: "right" });
  };

  drawTableHeader(y);
  y += 26;

  let currentPage = 1;
  const rowHeight = 20;
  const bottomLimit = h - 55;

  payments.forEach((p, idx) => {
    if (y + rowHeight > bottomLimit) {
      doc.addPage();
      currentPage++;
      drawHeader(currentPage);
      y = 105;
      drawTableHeader(y);
      y += 26;
    }

    // Alternating Row background
    if (idx % 2 === 1) {
      doc.setFillColor(248, 250, 252);
      doc.rect(margin, y - 4, contentWidth, rowHeight, "F");
    }

    // Row borders
    doc.setDrawColor(241, 245, 249);
    doc.line(margin, y + 14, w - margin, y + 14);

    const tenantName = p.tenant_name || p.tenants?.full_name || "—";
    const propertyUnit =
      (p.property_name || p.properties?.name ? `${p.property_name || p.properties?.name} ` : "") +
      (p.unit_name || p.units?.unit_number || p.units?.room_number || "—");

    const methodLabel =
      p.method === "mpesa"
        ? "M-Pesa"
        : p.method === "kcb" || p.method === "kcb_buni"
        ? "KCB Paybill"
        : p.method
        ? p.method.toUpperCase()
        : "—";

    const dateStr = p.paid_at ? new Date(p.paid_at).toLocaleDateString("en-GB") : "—";
    const refStr = (p.reference || "—").slice(0, 12);
    const periodStr = p.period_label || "—";
    const amtNum = Number(p.amount || 0);

    doc.setFont("helvetica", "normal");
    doc.setFontSize(7.5);
    doc.setTextColor(100, 116, 139);
    doc.text(String(idx + 1), colX.num, y + 8);

    doc.setTextColor(30, 41, 59);
    doc.text(dateStr, colX.date, y + 8);

    // Tenant Name (Bold)
    doc.setFont("helvetica", "bold");
    doc.text(tenantName.length > 20 ? tenantName.slice(0, 18) + "…" : tenantName, colX.tenant, y + 8);

    // Property / Unit
    doc.setFont("helvetica", "normal");
    doc.setTextColor(71, 85, 105);
    doc.text(propertyUnit.length > 18 ? propertyUnit.slice(0, 16) + "…" : propertyUnit, colX.unit, y + 8);

    // Method badge text
    if (p.method === "mpesa") {
      doc.setTextColor(5, 150, 105);
    } else if (p.method === "kcb" || p.method === "kcb_buni") {
      doc.setTextColor(37, 99, 235);
    } else {
      doc.setTextColor(100, 116, 139);
    }
    doc.text(methodLabel, colX.method, y + 8);

    // Reference
    doc.setFont("helvetica", "normal");
    doc.setTextColor(71, 85, 105);
    doc.text(refStr, colX.ref, y + 8);

    // Period
    doc.text(periodStr, colX.period, y + 8);

    // Amount (Right aligned bold)
    doc.setFont("helvetica", "bold");
    doc.setTextColor(15, 23, 42);
    doc.text(amtNum.toLocaleString("en-KE"), colX.amount, y + 8, { align: "right" });

    y += rowHeight;
  });

  // Table Grand Total Footer Row
  if (y + 30 > bottomLimit) {
    doc.addPage();
    currentPage++;
    drawHeader(currentPage);
    y = 105;
  }

  y += 4;
  doc.setFillColor(236, 253, 245);
  doc.roundedRect(margin, y, contentWidth, 24, 4, 4, "F");
  doc.setDrawColor(16, 185, 129);
  doc.roundedRect(margin, y, contentWidth, 24, 4, 4, "S");

  doc.setFont("helvetica", "bold");
  doc.setFontSize(9);
  doc.setTextColor(6, 78, 59);
  doc.text(`GRAND TOTAL (${payments.length} PAYMENTS RECORDED)`, margin + 12, y + 16);

  doc.setFontSize(11);
  doc.setTextColor(5, 150, 105);
  doc.text(`${currency} ${totalAmount.toLocaleString("en-KE")}`, w - margin - 12, y + 16, {
    align: "right",
  });

  // Add QR Code & Signature Seal if space allows or on last page
  y += 34;
  if (y + 65 <= bottomLimit && qrDataUrl) {
    doc.addImage(qrDataUrl, "PNG", margin + 8, y, 48, 48);

    doc.setFont("helvetica", "bold");
    doc.setFontSize(8.5);
    doc.setTextColor(15, 23, 42);
    doc.text("Official Digital Verification Seal", margin + 64, y + 16);

    doc.setFont("helvetica", "normal");
    doc.setFontSize(7.5);
    doc.setTextColor(100, 116, 139);
    doc.text(
      "Scan this QR code with any smartphone camera to verify this financial statement's integrity on RentReceiptPro.",
      margin + 64,
      y + 28,
      { maxWidth: contentWidth - 80 },
    );
  }

  // Draw Page numbers on all pages
  const totalPages = doc.getNumberOfPages();
  for (let i = 1; i <= totalPages; i++) {
    doc.setPage(i);
    drawFooter(i, totalPages);
  }

  return doc;
}

export async function downloadLandlordPaymentsPdf(
  payments: LandlordPaymentReportItem[],
  meta?: LandlordReportMeta,
) {
  const doc = await buildLandlordPaymentsPdf(payments, meta);
  const dateSlug = new Date().toISOString().slice(0, 10);
  doc.save(`RentReceipt_Payments_Statement_${dateSlug}.pdf`);
}

