/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as AdminPortalRouteImport } from './routes/admin-portal'
import { Route as AffiliateRouteImport } from './routes/affiliate'
import { Route as AffiliateProgramRouteImport } from './routes/affiliate-program'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as CaretakerRouteImport } from './routes/caretaker'
import { Route as DownloadRouteImport } from './routes/download'
import { Route as PrivacyPolicyRouteImport } from './routes/privacy-policy'
import { Route as TenantRouteImport } from './routes/tenant'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as VerifyRouteImport } from './routes/verify'
import { Route as AuthenticatedAnnouncementsRouteImport } from './routes/_authenticated/announcements'
import { Route as AuthenticatedBillingRouteImport } from './routes/_authenticated/billing'
import { Route as AuthenticatedCaretakersRouteImport } from './routes/_authenticated/caretakers'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as AuthenticatedPaymentsRouteImport } from './routes/_authenticated/payments'
import { Route as AuthenticatedPropertiesRouteImport } from './routes/_authenticated/properties'
import { Route as AuthenticatedReceiptsRouteImport } from './routes/_authenticated/receipts'
import { Route as AuthenticatedReportsRouteImport } from './routes/_authenticated/reports'
import { Route as AuthenticatedRequestsRouteImport } from './routes/_authenticated/requests'
import { Route as AuthenticatedSettingsRouteImport } from './routes/_authenticated/settings'
import { Route as AuthenticatedTenantsRouteImport } from './routes/_authenticated/tenants'
import { Route as AuthenticatedUnitsRouteImport } from './routes/_authenticated/units'
import { Route as AffiliateIndexRouteImport } from './routes/affiliate.index'
import { Route as AffiliateAuthRouteImport } from './routes/affiliate.auth'
import { Route as AuthCallbackRouteImport } from './routes/auth.callback'
import { Route as ReceiptPublicIdRouteImport } from './routes/receipt.$publicId'
import { Route as ApiPublicKcbIpnRouteImport } from './routes/api/public/kcb/ipn'
import { Route as ApiPublicMpesaCallbackRouteImport } from './routes/api/public/mpesa/callback'
import { Route as ApiPublicPaystackWebhookRouteImport } from './routes/api/public/paystack/webhook'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminPortalRoute = AdminPortalRouteImport.update({
  id: '/admin-portal',
  path: '/admin-portal',
  getParentRoute: () => rootRouteImport,
} as any)
const AffiliateRoute = AffiliateRouteImport.update({
  id: '/affiliate',
  path: '/affiliate',
  getParentRoute: () => rootRouteImport,
} as any)
const AffiliateProgramRoute = AffiliateProgramRouteImport.update({
  id: '/affiliate-program',
  path: '/affiliate-program',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const CaretakerRoute = CaretakerRouteImport.update({
  id: '/caretaker',
  path: '/caretaker',
  getParentRoute: () => rootRouteImport,
} as any)
const DownloadRoute = DownloadRouteImport.update({
  id: '/download',
  path: '/download',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyPolicyRoute = PrivacyPolicyRouteImport.update({
  id: '/privacy-policy',
  path: '/privacy-policy',
  getParentRoute: () => rootRouteImport,
} as any)
const TenantRoute = TenantRouteImport.update({
  id: '/tenant',
  path: '/tenant',
  getParentRoute: () => rootRouteImport,
} as any)
const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const VerifyRoute = VerifyRouteImport.update({
  id: '/verify',
  path: '/verify',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedAnnouncementsRoute =
  AuthenticatedAnnouncementsRouteImport.update({
    id: '/announcements',
    path: '/announcements',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedBillingRoute = AuthenticatedBillingRouteImport.update({
  id: '/billing',
  path: '/billing',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedCaretakersRoute = AuthenticatedCaretakersRouteImport.update({
  id: '/caretakers',
  path: '/caretakers',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedPaymentsRoute = AuthenticatedPaymentsRouteImport.update({
  id: '/payments',
  path: '/payments',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedPropertiesRoute = AuthenticatedPropertiesRouteImport.update({
  id: '/properties',
  path: '/properties',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedReceiptsRoute = AuthenticatedReceiptsRouteImport.update({
  id: '/receipts',
  path: '/receipts',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedReportsRoute = AuthenticatedReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedRequestsRoute = AuthenticatedRequestsRouteImport.update({
  id: '/requests',
  path: '/requests',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedSettingsRoute = AuthenticatedSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedTenantsRoute = AuthenticatedTenantsRouteImport.update({
  id: '/tenants',
  path: '/tenants',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedUnitsRoute = AuthenticatedUnitsRouteImport.update({
  id: '/units',
  path: '/units',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AffiliateIndexRoute = AffiliateIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AffiliateRoute,
} as any)
const AffiliateAuthRoute = AffiliateAuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => AffiliateRoute,
} as any)
const AuthCallbackRoute = AuthCallbackRouteImport.update({
  id: '/callback',
  path: '/callback',
  getParentRoute: () => AuthRoute,
} as any)
const ReceiptPublicIdRoute = ReceiptPublicIdRouteImport.update({
  id: '/receipt/$publicId',
  path: '/receipt/$publicId',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicKcbIpnRoute = ApiPublicKcbIpnRouteImport.update({
  id: '/api/public/kcb/ipn',
  path: '/api/public/kcb/ipn',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicMpesaCallbackRoute = ApiPublicMpesaCallbackRouteImport.update({
  id: '/api/public/mpesa/callback',
  path: '/api/public/mpesa/callback',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicPaystackWebhookRoute =
  ApiPublicPaystackWebhookRouteImport.update({
    id: '/api/public/paystack/webhook',
    path: '/api/public/paystack/webhook',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/admin-portal': typeof AdminPortalRoute
  '/affiliate': typeof AffiliateRouteWithChildren
  '/affiliate-program': typeof AffiliateProgramRoute
  '/auth': typeof AuthRouteWithChildren
  '/caretaker': typeof CaretakerRoute
  '/download': typeof DownloadRoute
  '/privacy-policy': typeof PrivacyPolicyRoute
  '/tenant': typeof TenantRoute
  '/terms': typeof TermsRoute
  '/verify': typeof VerifyRoute
  '/announcements': typeof AuthenticatedAnnouncementsRoute
  '/billing': typeof AuthenticatedBillingRoute
  '/caretakers': typeof AuthenticatedCaretakersRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/payments': typeof AuthenticatedPaymentsRoute
  '/properties': typeof AuthenticatedPropertiesRoute
  '/receipts': typeof AuthenticatedReceiptsRoute
  '/reports': typeof AuthenticatedReportsRoute
  '/requests': typeof AuthenticatedRequestsRoute
  '/settings': typeof AuthenticatedSettingsRoute
  '/tenants': typeof AuthenticatedTenantsRoute
  '/units': typeof AuthenticatedUnitsRoute
  '/affiliate/auth': typeof AffiliateAuthRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/receipt/$publicId': typeof ReceiptPublicIdRoute
  '/affiliate/': typeof AffiliateIndexRoute
  '/api/public/kcb/ipn': typeof ApiPublicKcbIpnRoute
  '/api/public/mpesa/callback': typeof ApiPublicMpesaCallbackRoute
  '/api/public/paystack/webhook': typeof ApiPublicPaystackWebhookRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/admin-portal': typeof AdminPortalRoute
  '/affiliate-program': typeof AffiliateProgramRoute
  '/auth': typeof AuthRouteWithChildren
  '/caretaker': typeof CaretakerRoute
  '/download': typeof DownloadRoute
  '/privacy-policy': typeof PrivacyPolicyRoute
  '/tenant': typeof TenantRoute
  '/terms': typeof TermsRoute
  '/verify': typeof VerifyRoute
  '/announcements': typeof AuthenticatedAnnouncementsRoute
  '/billing': typeof AuthenticatedBillingRoute
  '/caretakers': typeof AuthenticatedCaretakersRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/payments': typeof AuthenticatedPaymentsRoute
  '/properties': typeof AuthenticatedPropertiesRoute
  '/receipts': typeof AuthenticatedReceiptsRoute
  '/reports': typeof AuthenticatedReportsRoute
  '/requests': typeof AuthenticatedRequestsRoute
  '/settings': typeof AuthenticatedSettingsRoute
  '/tenants': typeof AuthenticatedTenantsRoute
  '/units': typeof AuthenticatedUnitsRoute
  '/affiliate/auth': typeof AffiliateAuthRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/receipt/$publicId': typeof ReceiptPublicIdRoute
  '/affiliate': typeof AffiliateIndexRoute
  '/api/public/kcb/ipn': typeof ApiPublicKcbIpnRoute
  '/api/public/mpesa/callback': typeof ApiPublicMpesaCallbackRoute
  '/api/public/paystack/webhook': typeof ApiPublicPaystackWebhookRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/admin': typeof AdminRoute
  '/admin-portal': typeof AdminPortalRoute
  '/affiliate': typeof AffiliateRouteWithChildren
  '/affiliate-program': typeof AffiliateProgramRoute
  '/auth': typeof AuthRouteWithChildren
  '/caretaker': typeof CaretakerRoute
  '/download': typeof DownloadRoute
  '/privacy-policy': typeof PrivacyPolicyRoute
  '/tenant': typeof TenantRoute
  '/terms': typeof TermsRoute
  '/verify': typeof VerifyRoute
  '/_authenticated/announcements': typeof AuthenticatedAnnouncementsRoute
  '/_authenticated/billing': typeof AuthenticatedBillingRoute
  '/_authenticated/caretakers': typeof AuthenticatedCaretakersRoute
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/_authenticated/payments': typeof AuthenticatedPaymentsRoute
  '/_authenticated/properties': typeof AuthenticatedPropertiesRoute
  '/_authenticated/receipts': typeof AuthenticatedReceiptsRoute
  '/_authenticated/reports': typeof AuthenticatedReportsRoute
  '/_authenticated/requests': typeof AuthenticatedRequestsRoute
  '/_authenticated/settings': typeof AuthenticatedSettingsRoute
  '/_authenticated/tenants': typeof AuthenticatedTenantsRoute
  '/_authenticated/units': typeof AuthenticatedUnitsRoute
  '/affiliate/auth': typeof AffiliateAuthRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/receipt/$publicId': typeof ReceiptPublicIdRoute
  '/affiliate/': typeof AffiliateIndexRoute
  '/api/public/kcb/ipn': typeof ApiPublicKcbIpnRoute
  '/api/public/mpesa/callback': typeof ApiPublicMpesaCallbackRoute
  '/api/public/paystack/webhook': typeof ApiPublicPaystackWebhookRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/admin-portal'
    | '/affiliate'
    | '/affiliate-program'
    | '/auth'
    | '/caretaker'
    | '/download'
    | '/privacy-policy'
    | '/tenant'
    | '/terms'
    | '/verify'
    | '/announcements'
    | '/billing'
    | '/caretakers'
    | '/dashboard'
    | '/payments'
    | '/properties'
    | '/receipts'
    | '/reports'
    | '/requests'
    | '/settings'
    | '/tenants'
    | '/units'
    | '/affiliate/auth'
    | '/auth/callback'
    | '/receipt/$publicId'
    | '/affiliate/'
    | '/api/public/kcb/ipn'
    | '/api/public/mpesa/callback'
    | '/api/public/paystack/webhook'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin'
    | '/admin-portal'
    | '/affiliate-program'
    | '/auth'
    | '/caretaker'
    | '/download'
    | '/privacy-policy'
    | '/tenant'
    | '/terms'
    | '/verify'
    | '/announcements'
    | '/billing'
    | '/caretakers'
    | '/dashboard'
    | '/payments'
    | '/properties'
    | '/receipts'
    | '/reports'
    | '/requests'
    | '/settings'
    | '/tenants'
    | '/units'
    | '/affiliate/auth'
    | '/auth/callback'
    | '/receipt/$publicId'
    | '/affiliate'
    | '/api/public/kcb/ipn'
    | '/api/public/mpesa/callback'
    | '/api/public/paystack/webhook'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/admin'
    | '/admin-portal'
    | '/affiliate'
    | '/affiliate-program'
    | '/auth'
    | '/caretaker'
    | '/download'
    | '/privacy-policy'
    | '/tenant'
    | '/terms'
    | '/verify'
    | '/_authenticated/announcements'
    | '/_authenticated/billing'
    | '/_authenticated/caretakers'
    | '/_authenticated/dashboard'
    | '/_authenticated/payments'
    | '/_authenticated/properties'
    | '/_authenticated/receipts'
    | '/_authenticated/reports'
    | '/_authenticated/requests'
    | '/_authenticated/settings'
    | '/_authenticated/tenants'
    | '/_authenticated/units'
    | '/affiliate/auth'
    | '/auth/callback'
    | '/receipt/$publicId'
    | '/affiliate/'
    | '/api/public/kcb/ipn'
    | '/api/public/mpesa/callback'
    | '/api/public/paystack/webhook'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AdminRoute: typeof AdminRoute
  AdminPortalRoute: typeof AdminPortalRoute
  AffiliateRoute: typeof AffiliateRouteWithChildren
  AffiliateProgramRoute: typeof AffiliateProgramRoute
  AuthRoute: typeof AuthRouteWithChildren
  CaretakerRoute: typeof CaretakerRoute
  DownloadRoute: typeof DownloadRoute
  PrivacyPolicyRoute: typeof PrivacyPolicyRoute
  TenantRoute: typeof TenantRoute
  TermsRoute: typeof TermsRoute
  VerifyRoute: typeof VerifyRoute
  ReceiptPublicIdRoute: typeof ReceiptPublicIdRoute
  ApiPublicKcbIpnRoute: typeof ApiPublicKcbIpnRoute
  ApiPublicMpesaCallbackRoute: typeof ApiPublicMpesaCallbackRoute
  ApiPublicPaystackWebhookRoute: typeof ApiPublicPaystackWebhookRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin-portal': {
      id: '/admin-portal'
      path: '/admin-portal'
      fullPath: '/admin-portal'
      preLoaderRoute: typeof AdminPortalRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/affiliate': {
      id: '/affiliate'
      path: '/affiliate'
      fullPath: '/affiliate'
      preLoaderRoute: typeof AffiliateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/affiliate-program': {
      id: '/affiliate-program'
      path: '/affiliate-program'
      fullPath: '/affiliate-program'
      preLoaderRoute: typeof AffiliateProgramRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/caretaker': {
      id: '/caretaker'
      path: '/caretaker'
      fullPath: '/caretaker'
      preLoaderRoute: typeof CaretakerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/download': {
      id: '/download'
      path: '/download'
      fullPath: '/download'
      preLoaderRoute: typeof DownloadRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy-policy': {
      id: '/privacy-policy'
      path: '/privacy-policy'
      fullPath: '/privacy-policy'
      preLoaderRoute: typeof PrivacyPolicyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tenant': {
      id: '/tenant'
      path: '/tenant'
      fullPath: '/tenant'
      preLoaderRoute: typeof TenantRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/verify': {
      id: '/verify'
      path: '/verify'
      fullPath: '/verify'
      preLoaderRoute: typeof VerifyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/announcements': {
      id: '/_authenticated/announcements'
      path: '/announcements'
      fullPath: '/announcements'
      preLoaderRoute: typeof AuthenticatedAnnouncementsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/billing': {
      id: '/_authenticated/billing'
      path: '/billing'
      fullPath: '/billing'
      preLoaderRoute: typeof AuthenticatedBillingRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/caretakers': {
      id: '/_authenticated/caretakers'
      path: '/caretakers'
      fullPath: '/caretakers'
      preLoaderRoute: typeof AuthenticatedCaretakersRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/payments': {
      id: '/_authenticated/payments'
      path: '/payments'
      fullPath: '/payments'
      preLoaderRoute: typeof AuthenticatedPaymentsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/properties': {
      id: '/_authenticated/properties'
      path: '/properties'
      fullPath: '/properties'
      preLoaderRoute: typeof AuthenticatedPropertiesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/receipts': {
      id: '/_authenticated/receipts'
      path: '/receipts'
      fullPath: '/receipts'
      preLoaderRoute: typeof AuthenticatedReceiptsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/reports': {
      id: '/_authenticated/reports'
      path: '/reports'
      fullPath: '/reports'
      preLoaderRoute: typeof AuthenticatedReportsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/requests': {
      id: '/_authenticated/requests'
      path: '/requests'
      fullPath: '/requests'
      preLoaderRoute: typeof AuthenticatedRequestsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/settings': {
      id: '/_authenticated/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AuthenticatedSettingsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/tenants': {
      id: '/_authenticated/tenants'
      path: '/tenants'
      fullPath: '/tenants'
      preLoaderRoute: typeof AuthenticatedTenantsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/units': {
      id: '/_authenticated/units'
      path: '/units'
      fullPath: '/units'
      preLoaderRoute: typeof AuthenticatedUnitsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/affiliate/': {
      id: '/affiliate/'
      path: '/'
      fullPath: '/affiliate/'
      preLoaderRoute: typeof AffiliateIndexRouteImport
      parentRoute: typeof AffiliateRoute
    }
    '/affiliate/auth': {
      id: '/affiliate/auth'
      path: '/auth'
      fullPath: '/affiliate/auth'
      preLoaderRoute: typeof AffiliateAuthRouteImport
      parentRoute: typeof AffiliateRoute
    }
    '/auth/callback': {
      id: '/auth/callback'
      path: '/callback'
      fullPath: '/auth/callback'
      preLoaderRoute: typeof AuthCallbackRouteImport
      parentRoute: typeof AuthRoute
    }
    '/receipt/$publicId': {
      id: '/receipt/$publicId'
      path: '/receipt/$publicId'
      fullPath: '/receipt/$publicId'
      preLoaderRoute: typeof ReceiptPublicIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/kcb/ipn': {
      id: '/api/public/kcb/ipn'
      path: '/api/public/kcb/ipn'
      fullPath: '/api/public/kcb/ipn'
      preLoaderRoute: typeof ApiPublicKcbIpnRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/mpesa/callback': {
      id: '/api/public/mpesa/callback'
      path: '/api/public/mpesa/callback'
      fullPath: '/api/public/mpesa/callback'
      preLoaderRoute: typeof ApiPublicMpesaCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/paystack/webhook': {
      id: '/api/public/paystack/webhook'
      path: '/api/public/paystack/webhook'
      fullPath: '/api/public/paystack/webhook'
      preLoaderRoute: typeof ApiPublicPaystackWebhookRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAnnouncementsRoute: typeof AuthenticatedAnnouncementsRoute
  AuthenticatedBillingRoute: typeof AuthenticatedBillingRoute
  AuthenticatedCaretakersRoute: typeof AuthenticatedCaretakersRoute
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedPaymentsRoute: typeof AuthenticatedPaymentsRoute
  AuthenticatedPropertiesRoute: typeof AuthenticatedPropertiesRoute
  AuthenticatedReceiptsRoute: typeof AuthenticatedReceiptsRoute
  AuthenticatedReportsRoute: typeof AuthenticatedReportsRoute
  AuthenticatedRequestsRoute: typeof AuthenticatedRequestsRoute
  AuthenticatedSettingsRoute: typeof AuthenticatedSettingsRoute
  AuthenticatedTenantsRoute: typeof AuthenticatedTenantsRoute
  AuthenticatedUnitsRoute: typeof AuthenticatedUnitsRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAnnouncementsRoute: AuthenticatedAnnouncementsRoute,
  AuthenticatedBillingRoute: AuthenticatedBillingRoute,
  AuthenticatedCaretakersRoute: AuthenticatedCaretakersRoute,
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedPaymentsRoute: AuthenticatedPaymentsRoute,
  AuthenticatedPropertiesRoute: AuthenticatedPropertiesRoute,
  AuthenticatedReceiptsRoute: AuthenticatedReceiptsRoute,
  AuthenticatedReportsRoute: AuthenticatedReportsRoute,
  AuthenticatedRequestsRoute: AuthenticatedRequestsRoute,
  AuthenticatedSettingsRoute: AuthenticatedSettingsRoute,
  AuthenticatedTenantsRoute: AuthenticatedTenantsRoute,
  AuthenticatedUnitsRoute: AuthenticatedUnitsRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

interface AffiliateRouteChildren {
  AffiliateAuthRoute: typeof AffiliateAuthRoute
  AffiliateIndexRoute: typeof AffiliateIndexRoute
}

const AffiliateRouteChildren: AffiliateRouteChildren = {
  AffiliateAuthRoute: AffiliateAuthRoute,
  AffiliateIndexRoute: AffiliateIndexRoute,
}

const AffiliateRouteWithChildren = AffiliateRoute._addFileChildren(
  AffiliateRouteChildren,
)

interface AuthRouteChildren {
  AuthCallbackRoute: typeof AuthCallbackRoute
}

const AuthRouteChildren: AuthRouteChildren = {
  AuthCallbackRoute: AuthCallbackRoute,
}

const AuthRouteWithChildren = AuthRoute._addFileChildren(AuthRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AdminRoute: AdminRoute,
  AdminPortalRoute: AdminPortalRoute,
  AffiliateRoute: AffiliateRouteWithChildren,
  AffiliateProgramRoute: AffiliateProgramRoute,
  AuthRoute: AuthRouteWithChildren,
  CaretakerRoute: CaretakerRoute,
  DownloadRoute: DownloadRoute,
  PrivacyPolicyRoute: PrivacyPolicyRoute,
  TenantRoute: TenantRoute,
  TermsRoute: TermsRoute,
  VerifyRoute: VerifyRoute,
  ReceiptPublicIdRoute: ReceiptPublicIdRoute,
  ApiPublicKcbIpnRoute: ApiPublicKcbIpnRoute,
  ApiPublicMpesaCallbackRoute: ApiPublicMpesaCallbackRoute,
  ApiPublicPaystackWebhookRoute: ApiPublicPaystackWebhookRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
